"""Initial migration

Revision ID: 0f36ba8f711c
Revises: 
Create Date: 2024-11-14 14:42:03.744753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f36ba8f711c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_ip', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('date_joined', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('ecommerce_products',
    sa.Column('product_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ebay_item_id', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('suggested_item_type', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('product_url', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('date_suggested', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('ebay_item_id')
    )
    op.create_index(op.f('ix_ecommerce_products_product_id'), 'ecommerce_products', ['product_id'], unique=False)
    op.create_table('fashion_trends',
    sa.Column('trend_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trend_name', sa.String(length=1000), nullable=False),
    sa.Column('trend_description', sa.Text(), nullable=False),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('trend_id')
    )
    op.create_table('outfits',
    sa.Column('outfit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occasion', sa.JSON(), nullable=True),
    sa.Column('for_weather', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('date_suggested', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('outfit_id')
    )
    op.create_index(op.f('ix_outfits_outfit_id'), 'outfits', ['outfit_id'], unique=False)
    op.create_table('weather_data',
    sa.Column('weather_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('temp_max', sa.Float(), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=False),
    sa.Column('feels_max', sa.Float(), nullable=False),
    sa.Column('feels_min', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=False),
    sa.Column('precipitation_probability', sa.Float(), nullable=False),
    sa.Column('special_condition', sa.String(length=255), nullable=True),
    sa.Column('weather_icon', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('weather_id')
    )
    op.create_index(op.f('ix_weather_data_weather_id'), 'weather_data', ['weather_id'], unique=False)
    op.create_table('wardrobe_items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('clothing_type', sa.String(length=255), nullable=False),
    sa.Column('for_weather', sa.String(length=255), nullable=True),
    sa.Column('color', sa.JSON(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['ecommerce_products.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_wardrobe_items_item_id'), 'wardrobe_items', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wardrobe_items_item_id'), table_name='wardrobe_items')
    op.drop_table('wardrobe_items')
    op.drop_index(op.f('ix_weather_data_weather_id'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_outfits_outfit_id'), table_name='outfits')
    op.drop_table('outfits')
    op.drop_table('fashion_trends')
    op.drop_index(op.f('ix_ecommerce_products_product_id'), table_name='ecommerce_products')
    op.drop_table('ecommerce_products')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###