"""Reduce trend_name length to 255

Revision ID: 31ba602beeef
Revises: 0f36ba8f711c
Create Date: 2024-11-14 15:00:32.328701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31ba602beeef'
down_revision: Union[str, None] = '0f36ba8f711c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fashion_trends', 'trend_name',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_fashion_trends_trend_name'), 'fashion_trends', ['trend_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fashion_trends_trend_name'), table_name='fashion_trends')
    op.alter_column('fashion_trends', 'trend_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###