"""Add ebay_item_id to EcommerceProduct model

Revision ID: 49dbfac3b999
Revises: 814b61673a32
Create Date: 2024-11-12 19:00:49.450294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49dbfac3b999'
down_revision: Union[str, None] = '814b61673a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###