"""Remove outfit_clothings association table

Revision ID: 4f3cd5570838
Revises: 4fa8d6374383
Create Date: 2024-11-12 18:23:52.168070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f3cd5570838'
down_revision: Union[str, None] = '4fa8d6374383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outfit_clothings')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_clothings',
        sa.Column('outfit_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['wardrobe_items.item_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['outfit_id'], ['outfits.outfit_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('outfit_id', 'item_id')
    )