"""Add OutfitSuggestion model and related changes

Revision ID: 8f746ca225d8
Revises: 31ba602beeef
Create Date: 2024-11-15 10:32:26.388781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f746ca225d8'
down_revision: Union[str, None] = '31ba602beeef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_suggestions',
    sa.Column('suggestion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outfit_details', sa.JSON(), nullable=False),
    sa.Column('date_suggested', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('suggestion_id')
    )
    op.create_index(op.f('ix_outfit_suggestions_suggestion_id'), 'outfit_suggestions', ['suggestion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfit_suggestions_suggestion_id'), table_name='outfit_suggestions')
    op.drop_table('outfit_suggestions')
    # ### end Alembic commands ###