"""Add trend_search_phrase to fashion_trends

Revision ID: 926ad1b04c58
Revises: eaa4fc00fecb
Create Date: 2024-11-16 21:55:18.178100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926ad1b04c58'
down_revision: Union[str, None] = 'eaa4fc00fecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fashion_trends', sa.Column('trend_search_phrase', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fashion_trends', 'trend_search_phrase')
    # ### end Alembic commands ###