"""Add user_id foreign key to EcommerceProduct

Revision ID: cd87d11e3c6b
Revises: fce22c2aee50
Create Date: 2024-11-04 23:31:28.216151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd87d11e3c6b'
down_revision: Union[str, None] = 'fce22c2aee50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecommerce_products', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ecommerce_products', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ecommerce_products', type_='foreignkey')
    op.drop_column('ecommerce_products', 'user_id')
    # ### end Alembic commands ###