"""Add gender to EcommerceProduct

Revision ID: d887372ddc42
Revises: 44d6f0fc8144
Create Date: 2024-11-17 10:47:21.097803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd887372ddc42'
down_revision: Union[str, None] = '44d6f0fc8144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecommerce_products', sa.Column('gender', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecommerce_products', 'gender')
    # ### end Alembic commands ###