"""Initial migration

Revision ID: db5087046729
Revises: 
Create Date: 2024-11-10 13:01:09.732861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = 'db5087046729'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ### commands auto generated by Alembic - manual adjustments required ###
    
    # Create users table
    op.create_table('users',
        sa.Column('user_id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False, unique=True),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('user_ip', sa.String(length=255), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('preferences', sa.JSON(), nullable=True),
        sa.Column('date_joined', sa.DateTime(), server_default=sa.func.now(), nullable=True)
    )

    # Create ecommerce_products table
    op.create_table('ecommerce_products',
        sa.Column('product_id', sa.BigInteger(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('product_name', sa.String(length=255), nullable=False),
        sa.Column('suggested_item_type', sa.String(length=255), nullable=True),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('product_url', sa.String(length=255), nullable=False),
        sa.Column('image_url', sa.String(length=255), nullable=True),
        sa.Column('date_suggested', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='ecommerce_products_ibfk_1')
    )

    # Create wardrobe_items table
    op.create_table('wardrobe_items',
        sa.Column('item_id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('product_id', sa.BigInteger(), nullable=True),
        sa.Column('clothing_type', sa.String(length=255), nullable=False),
        sa.Column('for_weather', sa.String(length=255), nullable=True),
        sa.Column('color', sa.JSON(), nullable=True),
        sa.Column('size', sa.String(length=50), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('image_url', sa.String(length=255), nullable=True),
        sa.Column('date_added', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_user_clothing'),
        sa.ForeignKeyConstraint(['product_id'], ['ecommerce_products.product_id'], name='fk_product_clothing', ondelete='SET NULL')
    )

    # Create outfits table
    op.create_table('outfits',
        sa.Column('outfit_id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('clothings', sa.JSON(), nullable=False),
        sa.Column('occasion', sa.JSON(), nullable=True),
        sa.Column('for_weather', sa.String(length=255), nullable=True),
        sa.Column('source_url', sa.String(length=255), nullable=True),
        sa.Column('date_suggested', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_user_outfit')
    )

    # Create fashion_trends table
    op.create_table('fashion_trends',
        sa.Column('trend_id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('trend_name', sa.String(length=1000), nullable=False),
        sa.Column('trend_description', sa.Text(), nullable=False),
        sa.Column('outfits', sa.JSON(), nullable=True),
        sa.Column('example_url', sa.String(length=255), nullable=True),
        sa.Column('date_added', sa.DateTime(), server_default=sa.func.now(), nullable=True)
    )

    # Create weather_data table
    op.create_table('weather_data',
        sa.Column('weather_id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('location', sa.String(length=255), nullable=False),
        sa.Column('temp_max', sa.Float(), nullable=False),
        sa.Column('temp_min', sa.Float(), nullable=False),
        sa.Column('feels_max', sa.Float(), nullable=False),
        sa.Column('feels_min', sa.Float(), nullable=False),
        sa.Column('wind_speed', sa.Float(), nullable=False),
        sa.Column('humidity', sa.Float(), nullable=False),
        sa.Column('precipitation', sa.Float(), nullable=False),
        sa.Column('precipitation_probability', sa.Float(), nullable=False),
        sa.Column('special_condition', sa.String(length=255), nullable=True),
        sa.Column('weather_icon', sa.String(length=255), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_weather_user', ondelete='SET NULL')
    )
    # ### end Alembic commands ###
    
def downgrade():
    # ### commands auto generated by Alembic - manual adjustments required ###
    
    # Drop weather_data table
    op.drop_table('weather_data')

    # Drop fashion_trends table
    op.drop_table('fashion_trends')

    # Drop outfits table
    op.drop_table('outfits')

    # Drop wardrobe_items table
    op.drop_table('wardrobe_items')

    # Drop ecommerce_products table
    op.drop_table('ecommerce_products')

    # Drop users table
    op.drop_table('users')
    # ### end Alembic commands ###