"""Initial migration

Revision ID: e7ae168470ff
Revises: 
Create Date: 2024-11-10 13:26:56.057748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ae168470ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ecommerce_products_product_id'), 'ecommerce_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_outfits_outfit_id'), 'outfits', ['outfit_id'], unique=False)
    op.drop_index('email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_wardrobe_items_item_id'), 'wardrobe_items', ['item_id'], unique=False)
    op.drop_constraint('fk_product_clothing', 'wardrobe_items', type_='foreignkey')
    op.create_foreign_key(None, 'wardrobe_items', 'ecommerce_products', ['product_id'], ['product_id'])
    op.create_index(op.f('ix_weather_data_weather_id'), 'weather_data', ['weather_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_weather_id'), table_name='weather_data')
    op.drop_constraint(None, 'wardrobe_items', type_='foreignkey')
    op.create_foreign_key('fk_product_clothing', 'wardrobe_items', 'ecommerce_products', ['product_id'], ['product_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_wardrobe_items_item_id'), table_name='wardrobe_items')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_outfits_outfit_id'), table_name='outfits')
    op.drop_index(op.f('ix_ecommerce_products_product_id'), table_name='ecommerce_products')
    # ### end Alembic commands ###