"""Make location mandatory in users

Revision ID: eaa4fc00fecb
Revises: 8f746ca225d8
Create Date: 2024-11-15 11:47:01.590384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa4fc00fecb'
down_revision: Union[str, None] = '8f746ca225d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###