"""Add gender column to outfit_suggestions

Revision ID: f015b8e60df9
Revises: d887372ddc42
Create Date: 2024-11-17 13:52:00.415450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f015b8e60df9'
down_revision: Union[str, None] = 'd887372ddc42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfit_suggestions', sa.Column('gender', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outfit_suggestions', 'gender')
    # ### end Alembic commands ###