"""Initial migration

Revision ID: fce22c2aee50
Revises: 
Create Date: 2024-11-04 23:02:01.656540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fce22c2aee50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to resolve FK issues ###

    # 1. Drop the foreign key on `product_id` in `wardrobe_items` referencing `ecommerce_products`
    op.drop_constraint('fk_product_clothing', 'wardrobe_items', type_='foreignkey')

    # 2. Drop the foreign key in `ecommerce_products` related to `user_id` (if this is intentional)
    op.drop_constraint('ecommerce_products_ibfk_1', 'ecommerce_products', type_='foreignkey')
    
    # 3. Alter `product_id` in `ecommerce_products`
    op.alter_column('ecommerce_products', 'product_id',
                    existing_type=mysql.BIGINT(),
                    nullable=False,
                    autoincrement=True)

    # 4. Drop the `user_id` column from `ecommerce_products` if needed
    op.drop_column('ecommerce_products', 'user_id')

    # 5. Add new columns in `fashion_trends`
    op.add_column('fashion_trends', sa.Column('outfits', sa.JSON(), nullable=True))
    op.add_column('fashion_trends', sa.Column('example_url', sa.String(length=255), nullable=True))

    # 6. Re-add the foreign key on `product_id` in `wardrobe_items` referencing `ecommerce_products`
    op.create_foreign_key(
        'fk_product_clothing', 'wardrobe_items', 'ecommerce_products', ['product_id'], ['product_id']
    )

    # 7. Drop and recreate foreign key in `weather_data` (on `user_id` with `ondelete=SET NULL`)
    op.drop_constraint('weather_data_ibfk_1', 'weather_data', type_='foreignkey')
    op.create_foreign_key(
        'fk_weather_user', 'weather_data', 'users', ['user_id'], ['user_id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to resolve FK issues ###

    # 1. Drop foreign key on `user_id` in `weather_data`
    op.drop_constraint('fk_weather_user', 'weather_data', type_='foreignkey')
    # Restore the old foreign key (without `ondelete=SET NULL`)
    op.create_foreign_key(
        'weather_data_ibfk_1', 'weather_data', 'users', ['user_id'], ['user_id']
    )

    # 2. Drop foreign key on `product_id` in `wardrobe_items`
    op.drop_constraint('fk_product_clothing', 'wardrobe_items', type_='foreignkey')

    # 3. Drop new columns in `fashion_trends`
    op.drop_column('fashion_trends', 'example_url')
    op.drop_column('fashion_trends', 'outfits')

    # 4. Restore `user_id` in `ecommerce_products` (if needed)
    op.add_column('ecommerce_products', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # Recreate the foreign key if it originally existed
    op.create_foreign_key('ecommerce_products_ibfk_1', 'ecommerce_products', 'users', ['user_id'], ['user_id'])

    # 5. Revert `product_id` in `ecommerce_products` back to the original type (if it was previously different)
    op.alter_column('ecommerce_products', 'product_id',
                    existing_type=mysql.BIGINT(),
                    nullable=True,
                    autoincrement=True)

    # 6. Re-add the original foreign key on `product_id` in `wardrobe_items`
    op.create_foreign_key(
        'fk_product_clothing', 'wardrobe_items', 'ecommerce_products', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='SET NULL'
    )
    # ### end Alembic commands ###
